15:24:22 : ERROR('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
